### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: 'request_logging.middleware.LoggingMiddleware' isn't a subclass of AppConfig.

### ISSUE THREAD

**Issue by Wissperwind** [Rhumbix/django-request-logging#129]
Hi,
Tried to add this middleware, but got an error:
```
Traceback (most recent call last):
  File "C:\Test_Installation\Test\psbp\resource\server\bpServer3\manage.py", line 22, in <module>
    main()
  File "C:\Test_Installation\Test\psbp\resource\server\bpServer3\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Test_Installation\pythonEnvironmentWithAllStuff\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Test_Installation\pythonEnvironmentWithAllStuff\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\Test_Installation\pythonEnvironmentWithAllStuff\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Test_Installation\pythonEnvironmentWithAllStuff\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Test_Installation\pythonEnvironmentWithAllStuff\lib\site-packages\django\apps\config.py", line 229, in create
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: 'request_logging.middleware.LoggingMiddleware' isn't a subclass of AppConfig.

Process finished with exit code 1
```

**Comment by sgelis** [comment]
Did you declare the middleware properly as mentioned in the README? It looks to me that you declared it in `INSTALLED_APPS` instead of `MIDDLEWARE`.

**Comment by Wissperwind** [comment]
Well, thats true. Thanks
