### ISSUE TITLE
RawPostDataException with 0.6.8

### ISSUE THREAD

**Issue by dmodin** [Rhumbix/django-request-logging#67]
We see this error when doing a post after upgrading from 0.6.7 to 0.6.8:
```
/request_logging/middleware.py:166: in process_body
@property
    def body(self):
        if not hasattr(self, '_body'):
            if self._read_started:
>               raise RawPostDataException("You cannot access body after reading from request's data stream")
E               django.http.request.RawPostDataException: You cannot access body after reading from request's data stream
```
 using django 2.2.1

**Comment by tclancy** [comment]
Is this happening on all requests or just some? It feels like this may be a setup issue.

**Comment by joseph-vedadi** [comment]
I got this error too, the moment I used  https://github.com/miki725/django-url-filter 

Based on an old post I added : 
REST_FRAMEWORK = {
 "FORM_METHOD_OVERRIDE": None,
"FORM_CONTENT_OVERRIDE": None,
"FORM_CONTENTTYPE_OVERRIDE": None,
 ...}

Could you please investigate this Thanks.

**Comment by tclancy** [comment]
Can one of you provide a test case that causes the issue? Guessing something in #65 is causing the body to be read and we don't have a test covering the problem.

**Comment by tclancy** [comment]
@kennethjiang can you guys take a look at this to see if the last PR caused an error?

**Comment by dmodin** [comment]
I'm currently trying to do a test reproducing the error

________________________________
De : Tom Clancy <notifications@github.com>
Envoyé : jeudi 2 mai 2019 23:11
À : Rhumbix/django-request-logging
Cc : dmod1; Author
Objet : Re: [Rhumbix/django-request-logging] RawPostDataException with 0.6.8 (#67)


@kennethjiang<https://github.com/kennethjiang> can you guys take a look at this to see if the last PR caused an error?

**Comment by dmodin** [comment]
Can't reproduce it easily in a clean project but I think the issue is when posting data including uploaded file

**Comment by therefromhere** [comment]
I've managed to reproduce the bug - see example project here: https://github.com/therefromhere/django_request_logging_bug

I think the django-request-logging tests need a bit of refactoring so they can accommodate an integration test like this?

**Comment by fotometabata** [comment]
thank you.
Resolved after downgrade the "django-request-logging" version from 6.9.0 to 6.7.0.

It seems that the version was upgraded because no version was specified in the "requirements.txt".

**Comment by palmchou** [comment]
Same exact issue. Attached trace stack below. 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/request_logging/middleware.py", line 99, in __call__
    self.process_body(request)
  File "/usr/local/lib/python3.6/site-packages/request_logging/middleware.py", line 166, in process_body
    if not request.body:
  File "/usr/local/lib/python3.6/site-packages/django/http/request.py", line 275, in body
    raise RawPostDataException("You cannot access body after reading from request's data stream")
django.http.request.RawPostDataException: You cannot access body after reading from request's data stream
```
In my case, the request is a POST as multipart/form with a file upload.

**Comment by kennethjiang** [comment]
> @kennethjiang can you guys take a look at this to see if the last PR caused an error?

Sorry for missing your question @tclancy . We can't reproduce this problem here.

**Comment by therefromhere** [comment]
@kennethjiang did you try using the example project I linked above?

I think the bug is triggered by a POST that contains no form fields (eg of file only).

**Comment by wwsean08** [comment]
Working on this now and figuring out how to fix it

**Comment by JocelynDelalande** [comment]
From my tests : I had the bug in 0.6.9, upgrading to 0.7.2 fixed it.

**Comment by krzysieqq** [comment]
Still in 0.7.3
